### ISSUE TITLE
Update Site Repository Issues Templates

### ISSUE THREAD

**Issue by mshidlov** [amplication/site#150]

**Comment by yuval-hazaz** [comment]
@Abhijay007 thanks for asking
Actually, we do not track issues in this repository - instead, all issues need to be open in the main project repo 
https://github.com/amplication/amplication

So, the template should include instructions and a link to select the issue type on the main repo.
https://github.com/amplication/amplication/issues/new/choose

if you want to handle that, you are more than welcome 🙏

**Comment by Abhijay007** [comment]
@yuval-hazaz  sure :)
